#ifndef CONFIG_H
#define CONFIG_H

#define LOG_LIBS_PRINT_CUSTOM
#define LOG_LIBS_PRINT_UART
#define LOG_LIBS_USE_PRINTF 2

#define SYSTEM_LED_BLINK_PEROD 500 // ms
#define READ_COMMAND_BUF_LEN 32
#endif // !CONFIG_H